apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: packwerk
  description: "Good things come in small packages."
  annotations:
    github.com/project-slug: justworkshr/packwerk
  tags:
    - ruby
spec:
  lifecycle: production
  type: service
  owner: unknown